### ISSUE TITLE
Cursor needs some work

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#476]
Hi @yneves When I manually check a reference off as cited, the cursor/screen moves to the first U.S. section's blank cell.  Same when I click a T in the foreign and NPL sections, the cursors/screen jumps to the first available cell in the US section.

When I enter a new U.S. reference, the cursor moves to the foreign section's blank cell.

When I finish adding the Filing Date in the Matter section, cursor move to first available blank cell in U.S. section.  Please turn this off.  Thanks

**Comment by yneves** [comment]
Done here #478

**Comment by JulieJager** [comment]
Not sure if fixes were rolled out but here are a few more areas that need work.
1.  After entering a note in Client ID, cursor jumps to empty field in US documents
2.  After entering a US Document Number, cursor jumps to foreign section.

**Comment by yneves** [comment]
Yeah, those two are also fixed, it will be rolled out next week when Nam is back.

**Comment by JulieJager** [comment]
@yneves After Release, this is still happening:  after entering a US Document Number, cursor jumps to foreign section.

**Comment by JulieJager** [comment]
@yneves cursor still jumps from US section to foreign section in certain views (i.e., when entering data to a cell that is either at the top of the screen or bottom).  location of the empty cell seem to dictate where it goes.  I could be crazy too. ;)
