### ISSUE TITLE
Service brochures, Quick Refs. Guide, and User Manual are not available

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#658]
I received a report of a user not being able to access the above.   I could not either.

**Comment by ntgn81** [comment]
@JulieJager , weird, I can see them. Can you give it another try please? Might need a hard reload with CTRL-F5.

**Comment by ntgn81** [comment]
Can you try again , please? SHould be fixed now

**Comment by JulieJager** [comment]
Trying to test, but can't get dashboard to resolve any data.   ???

**Comment by ntgn81** [comment]
Yep, pushing a fix. Thanks for checking that. Will be up in a few mins.

**Comment by JulieJager** [comment]
Still can't view consistently.  Sometimes they open, subsequently tries dont work.  Can you try to open any one of the documents twice?

**Comment by ntgn81** [comment]
Any document in particular? I"ll try user manual

**Comment by JulieJager** [comment]
Try all of them.

**Comment by ntgn81** [comment]
Chrome? I'm seeing them all the time

**Comment by JulieJager** [comment]
I'm in chrome.  Maybe its just me - which is okay.

**Comment by ntgn81** [comment]
Do you see this on URL?

https://docs.google.com/viewer?url=http%3A%2F%2Fwww.syncids.com%2FSyncIDS_Quick_Tips_4.0.pdf

https://docs.google.com/viewer?url=http%3A%2F%2Fwww.syncids.com%2FSyncIDS_User_Manual_4.0.pdf

**Comment by JulieJager** [comment]
yep.

**Comment by JulieJager** [comment]
I think I must be moving too fast from one URL to another.  Let's just keep an eye on it for now.  I appreciate your help. :)

**Comment by ntgn81** [comment]
For sure!
